version: 2
reference:

  ## Workspaces
  workspace: &workspace
               ~/code

  ## Docker Configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  ## Docker Cache
  docker_generate_cache_key: &docker_generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  docker_gradle_key: &docker_gradle_key
                       docker-gradle-{{ checksum "/tmp/checksum.txt" }}

  docker_restore_gradle_cache: &docker_restore_gradle_cache
    restore_cache:
      key: *docker_gradle_key

  docker_save_gradle_cache: &docker_save_gradle_cache
    save_cache:
      key: *docker_gradle_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache

  ## MacOS Configurations
  ios_config: &ios_config
    working_directory: *workspace
    macos:
      xcode: "10.3.0"
    shell: /bin/bash --login -eo pipefail
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  ## MacOS Steps
  macos_install_android: &macos_install_android
    run:
      name: Install Android sdk
      command: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask
        HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk

  macos_prepare_environment_variables: &macos_prepare_environment_variables
    run:
      name: Setup environment variables
      command: |
        echo 'export ANDROID_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
        echo 'export ANDROID_SDK_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
        echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $BASH_ENV
        echo 'export JAVA_HOME=$(/usr/libexec/java_home -V)' >> $BASH_ENV

  macos_install_android_dependencies: &macos_install_android_dependencies
    run:
      name: Install Android dependencies
      command: (yes | sdkmanager "platform-tools" "platforms;android-28" --verbose) || true

  ## MacOS Cache
  macos_generate_cache_key: &macos_generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  macos_gradle_key: &macos_gradle_key
                      macos-gradle-{{ checksum "/tmp/checksum.txt" }}

  macos_restore_gradle_cache: &macos_restore_gradle_cache
    restore_cache:
      key: *macos_gradle_key

  macos_save_gradle_cache: &macos_save_gradle_cache
    save_cache:
      key: *macos_gradle_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache

  ## Dependencies
  download_android_dependencies: &download_android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

jobs:
  lint:
    <<: *android_config
    steps:
      - checkout
      - *docker_generate_cache_key
      - *docker_restore_gradle_cache
      - *download_android_dependencies
      - *docker_save_gradle_cache
      - run:
          name: Run Lint
          command: ./gradlew detekt --console=plain -Dorg.gradle.parallel=false

  test_android:
    <<: *android_config
    steps:
      - checkout
      - *docker_generate_cache_key
      - *docker_restore_gradle_cache
      - *download_android_dependencies
      - *docker_save_gradle_cache
      - run:
          name:  "Run Android Unit Test"
          command: ./gradlew testDebugUnitTest --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  test_js:
    <<: *android_config
    steps:
      - checkout
      - *docker_generate_cache_key
      - *docker_restore_gradle_cache
      - *download_android_dependencies
      - *docker_save_gradle_cache
      - run:
          name:  "Run JS Unit Test"
          command: ./gradlew jsTest --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  test_ios:
    <<: *ios_config
    steps:
      - checkout
      - *macos_install_android
      - *macos_prepare_environment_variables
      - *macos_install_android_dependencies
      - *macos_generate_cache_key
      - *macos_restore_gradle_cache
      - *download_android_dependencies
      - *macos_save_gradle_cache
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: "Test iOS target"
          command: ./run-native-ios-tests.sh

  build_android:
    <<: *android_config
    steps:
      - checkout
      - *docker_generate_cache_key
      - *docker_restore_gradle_cache
      - *download_android_dependencies
      - *docker_save_gradle_cache
      - run:
          name:  "Build Android Project"
          command: ./gradlew :android:assemble --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  build_js:
    <<: *android_config
    steps:
      - checkout
      - *docker_generate_cache_key
      - *docker_restore_gradle_cache
      - *download_android_dependencies
      - *docker_save_gradle_cache
      - run:
          name:  "Build JS Project"
          command: ./gradlew :frontend:assemble --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  build_ios:
    <<: *ios_config
    steps:
      - checkout
      - *macos_install_android
      - *macos_prepare_environment_variables
      - *macos_install_android_dependencies
      - *macos_generate_cache_key
      - *macos_restore_gradle_cache
      - *download_android_dependencies
      - *macos_save_gradle_cache
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: "Build iOS Project"
          command: ./build-native-ios.sh

workflows:
  version: 2
  test_build:
    jobs:
      - lint
      - test_android
      - test_js
      - test_ios
      - build_android:
          requires:
            - lint
            - test_android
      - build_js:
          requires:
            - lint
            - test_js
      - build_ios:
          requires:
            - lint
            - test_ios