version: 2
reference:

  ################
  # Workspace
  ################

  workspace: &workspace
               ~/code

  ###########################
  # Android Configurations #
  ##########################

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  android_generate_cache_key: &android_generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  android_gradle_key: &android_gradle_key
                        android-gradle-v1-{{ checksum "/tmp/checksum.txt" }}

  android_restore_gradle_cache: &android_restore_gradle_cache
    restore_cache:
      key: *android_gradle_key

  android_save_gradle_cache: &android_save_gradle_cache
    save_cache:
      key: *android_gradle_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache


  ######################
  # iOS Configurations #
  ######################

  ios_config: &ios_config
    working_directory: *workspace
    macos:
      xcode: "11.3.1"
    shell: /bin/bash --login -eo pipefail
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  ios_install_android: &ios_install_android
    run:
      name: Install Android sdk
      command: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask
        HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk

  ios_prepare_environment_variables: &ios_prepare_environment_variables
    run:
      name: Setup environment variables
      command: |
        echo 'export ANDROID_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
        echo 'export ANDROID_SDK_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
        echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $BASH_ENV
        echo 'export JAVA_HOME=$(/usr/libexec/java_home -V)' >> $BASH_ENV

  ios_install_android_dependencies: &ios_install_android_dependencies
    run:
      name: Install Android dependencies
      command: (yes | sdkmanager "platform-tools" "platforms;android-28" --verbose) || true

  ios_generate_cache_key: &ios_generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  ios_gradle_key: &ios_gradle_key
                    ios-gradle-v1-{{ checksum "/tmp/checksum.txt" }}

  ios_restore_gradle_cache: &ios_restore_gradle_cache
    restore_cache:
      key: *ios_gradle_key

  ios_save_gradle_cache: &ios_save_gradle_cache
    save_cache:
      key: *ios_gradle_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache


  ######################
  # web Configurations #
  ######################

  web_config: &web_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8u232-jdk-browsers
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  web_generate_cache_key: &web_generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  web_gradle_key: &web_gradle_key
                    web-gradle-v1-{{ checksum "/tmp/checksum.txt" }}

  web_restore_gradle_cache: &web_restore_gradle_cache
    restore_cache:
      key: *web_gradle_key

  web_save_gradle_cache: &web_save_gradle_cache
    save_cache:
      key: *web_gradle_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache

  #######################
  # Lint Configurations #
  #######################

  lint_config: &lint_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8u232-jdk
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  lint_generate_cache_key: &lint_generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  lint_gradle_key: &lint_gradle_key
                     lint-gradle-v1-{{ checksum "/tmp/checksum.txt" }}

  lint_restore_gradle_cache: &lint_restore_gradle_cache
    restore_cache:
      key: *lint_gradle_key

  lint_save_gradle_cache: &lint_save_gradle_cache
    save_cache:
      key: *lint_gradle_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache

  #######################
  # Backend Configurations #
  #######################

  backend_config: &backend_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8u232-jdk
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  backend_generate_cache_key: &backend_generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  backend_gradle_key: &backend_gradle_key
                     lint-gradle-v1-{{ checksum "/tmp/checksum.txt" }}

  backend_restore_gradle_cache: &backend_restore_gradle_cache
    restore_cache:
      key: *backend_gradle_key

  backend_save_gradle_cache: &backend_save_gradle_cache
    save_cache:
      key: *backend_gradle_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache

  #########################
  # Download dependencies #
  #########################

  download_android_dependencies: &download_android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies


  ########
  # Jobs #
  ########

jobs:
  lint:
    <<: *lint_config
    steps:
      - checkout
      - *lint_generate_cache_key
      - *lint_restore_gradle_cache
      - *download_android_dependencies
      - *lint_save_gradle_cache
      - run:
          name: Run Lint
          command: ./gradlew detekt --console=plain -Dorg.gradle.parallel=false

  test_backend:
    <<: *backend_config
    steps:
      - checkout
      - *backend_generate_cache_key
      - *backend_restore_gradle_cache
      - *download_android_dependencies
      - *backend_save_gradle_cache
      - run:
          name: Run Lint
          command: ./gradlew :backend:test --console=plain -Dorg.gradle.parallel=false

  test_android:
    <<: *android_config
    steps:
      - checkout
      - *android_generate_cache_key
      - *android_restore_gradle_cache
      - *download_android_dependencies
      - *android_save_gradle_cache
      - run:
          name:  "Run Android Unit Test"
          command: ./gradlew testDebugUnitTest --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  test_web:
    <<: *web_config
    steps:
      - checkout
      - *web_generate_cache_key
      - *web_restore_gradle_cache
      - *download_android_dependencies
      - *web_save_gradle_cache
      - run:
          name:  "Run JS Unit Test"
          command: ./gradlew jsTest --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  test_ios:
    <<: *ios_config
    steps:
      - checkout
      - *ios_install_android
      - *ios_prepare_environment_variables
      - *ios_install_android_dependencies
      - *ios_generate_cache_key
      - *ios_restore_gradle_cache
      - *download_android_dependencies
      - *ios_save_gradle_cache
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: "Test iOS target"
          command: ./run-native-ios-tests.sh

  build_android:
    <<: *android_config
    steps:
      - checkout
      - *android_generate_cache_key
      - *android_restore_gradle_cache
      - *download_android_dependencies
      - *android_save_gradle_cache
      - run:
          name:  "Build Android Project"
          command: ./gradlew :android:assemble --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  build_web:
    <<: *android_config
    steps:
      - checkout
      - *web_generate_cache_key
      - *web_restore_gradle_cache
      - *download_android_dependencies
      - *web_save_gradle_cache
      - run:
          name:  "Build JS Project"
          command: ./gradlew clean :frontend:assemble --console=plain -Dorg.gradle.parallel=false
          no_output_timeout: 15m

  build_ios:
    <<: *ios_config
    steps:
      - checkout
      - *ios_install_android
      - *ios_prepare_environment_variables
      - *ios_install_android_dependencies
      - *ios_generate_cache_key
      - *ios_restore_gradle_cache
      - *download_android_dependencies
      - *ios_save_gradle_cache
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: "Build iOS Project"
          command: ./build-native-ios.sh


  #############
  # Workflows #
  #############

workflows:
  version: 2
  test_build:
    jobs:
      - lint
      - test_backend:
          requires:
            - lint
      - test_android:
          requires:
            - lint
      - test_web:
          requires:
            - lint
      - build_android:
          requires:
            - lint
            - test_android
      - build_web:
          requires:
            - lint
            - test_web
      - build_ios:
          requires:
            - lint